const config = {
    apiKey: "AIzaSyBOA8VWhygsxwc7jW6B2wVhOstgq_BnrOA",
    authDomain: "",
    databaseURL: "https://myfirstproject-9b0d7.firebaseio.com",
    projectId: "myfirstproject-9b0d7",
    storageBucket: "",
    messagingSenderId: "1011109052912"
};

firebase.initializeApp(config);
const firestore = firebase.firestore();
const cars = [{"id":1,"make":"Suzuki","model":"Vitara","year":1999,"color":"Violet","stolen":"Monthly"},
{"id":2,"make":"Honda","model":"CR-V","year":2003,"color":"Puce","stolen":"Weekly"},
{"id":3,"make":"Acura","model":"SLX","year":1997,"color":"Yellow","stolen":"Never"},
{"id":4,"make":"Volkswagen","model":"Golf","year":1986,"color":"Mauv","stolen":"Monthly"},
{"id":5,"make":"Honda","model":"S2000","year":2001,"color":"Fuscia","stolen":"Daily"},
{"id":6,"make":"Toyota","model":"Highlander","year":2012,"color":"Teal","stolen":"Once"},
{"id":7,"make":"Saturn","model":"S-Series","year":1999,"color":"Indigo","stolen":"Often"},
{"id":8,"make":"Lamborghini","model":"Gallardo","year":2008,"color":"Yellow","stolen":"Daily"},
{"id":9,"make":"Volvo","model":"V40","year":2001,"color":"Teal","stolen":"Weekly"},
{"id":10,"make":"Land Rover","model":"Range Rover","year":1999,"color":"Blue","stolen":"Often"},
{"id":11,"make":"Acura","model":"MDX","year":2010,"color":"Aquamarine","stolen":"Weekly"},
{"id":12,"make":"Mitsubishi","model":"Cordia","year":1986,"color":"Fuscia","stolen":"Seldom"},
{"id":13,"make":"Nissan","model":"NV3500","year":2012,"color":"Maroon","stolen":"Yearly"},
{"id":14,"make":"Pontiac","model":"Grand Am","year":1998,"color":"Indigo","stolen":"Once"},
{"id":15,"make":"Chrysler","model":"300M","year":2001,"color":"Maroon","stolen":"Once"},
{"id":16,"make":"Chevrolet","model":"Suburban 2500","year":2000,"color":"Aquamarine","stolen":"Seldom"},
{"id":17,"make":"Ford","model":"Escort","year":1995,"color":"Indigo","stolen":"Seldom"},
{"id":18,"make":"Mercedes-Benz","model":"C-Class","year":1997,"color":"Pink","stolen":"Never"},
{"id":19,"make":"Aston Martin","model":"DB9 Volante","year":2006,"color":"Green","stolen":"Seldom"},
{"id":20,"make":"Chevrolet","model":"Suburban","year":2008,"color":"Mauv","stolen":"Yearly"},
{"id":21,"make":"Land Rover","model":"Freelander","year":2011,"color":"Crimson","stolen":"Weekly"},
{"id":22,"make":"Eagle","model":"Talon","year":1992,"color":"Purple","stolen":"Once"},
{"id":23,"make":"Aston Martin","model":"DBS","year":2009,"color":"Puce","stolen":"Often"},
{"id":24,"make":"Volvo","model":"XC60","year":2009,"color":"Purple","stolen":"Never"},
{"id":25,"make":"Chrysler","model":"Crossfire","year":2004,"color":"Khaki","stolen":"Once"},
{"id":26,"make":"Mercedes-Benz","model":"CLK-Class","year":2008,"color":"Green","stolen":"Weekly"},
{"id":27,"make":"Lotus","model":"Elan","year":1992,"color":"Yellow","stolen":"Once"},
{"id":28,"make":"Buick","model":"LaCrosse","year":2009,"color":"Orange","stolen":"Yearly"},
{"id":29,"make":"Dodge","model":"Ram 2500 Club","year":1998,"color":"Turquoise","stolen":"Yearly"},
{"id":30,"make":"Subaru","model":"Impreza","year":1996,"color":"Turquoise","stolen":"Daily"},
{"id":31,"make":"Ford","model":"Econoline E250","year":1992,"color":"Orange","stolen":"Daily"},
{"id":32,"make":"Toyota","model":"4Runner","year":2002,"color":"Aquamarine","stolen":"Monthly"},
{"id":33,"make":"Mazda","model":"RX-7","year":1993,"color":"Pink","stolen":"Once"},
{"id":34,"make":"Mercedes-Benz","model":"CL-Class","year":2005,"color":"Goldenrod","stolen":"Once"},
{"id":35,"make":"Chevrolet","model":"HHR","year":2007,"color":"Indigo","stolen":"Never"},
{"id":36,"make":"Ford","model":"E250","year":2003,"color":"Blue","stolen":"Often"},
{"id":37,"make":"Dodge","model":"Caravan","year":1985,"color":"Goldenrod","stolen":"Yearly"},
{"id":38,"make":"Audi","model":"Q7","year":2007,"color":"Indigo","stolen":"Never"},
{"id":39,"make":"Volkswagen","model":"GTI","year":1986,"color":"Mauv","stolen":"Often"},
{"id":40,"make":"Isuzu","model":"Rodeo","year":1995,"color":"Fuscia","stolen":"Often"},
{"id":41,"make":"Chevrolet","model":"Venture","year":2003,"color":"Crimson","stolen":"Seldom"},
{"id":42,"make":"Chevrolet","model":"Monza","year":1975,"color":"Green","stolen":"Daily"},
{"id":43,"make":"Chevrolet","model":"Camaro","year":1976,"color":"Green","stolen":"Yearly"},
{"id":44,"make":"Mercedes-Benz","model":"CLK-Class","year":2001,"color":"Orange","stolen":"Seldom"},
{"id":45,"make":"BMW","model":"7 Series","year":2002,"color":"Puce","stolen":"Seldom"},
{"id":46,"make":"Mercedes-Benz","model":"S-Class","year":1994,"color":"Khaki","stolen":"Once"},
{"id":47,"make":"Toyota","model":"Camry","year":2006,"color":"Indigo","stolen":"Daily"},
{"id":48,"make":"Mercedes-Benz","model":"S-Class","year":1985,"color":"Green","stolen":"Weekly"},
{"id":49,"make":"Buick","model":"LaCrosse","year":2006,"color":"Violet","stolen":"Weekly"},
{"id":50,"make":"Nissan","model":"Cube","year":2012,"color":"Indigo","stolen":"Daily"},
{"id":51,"make":"Mazda","model":"B-Series","year":2006,"color":"Purple","stolen":"Seldom"},
{"id":52,"make":"Cadillac","model":"Escalade","year":2007,"color":"Purple","stolen":"Seldom"},
{"id":53,"make":"Dodge","model":"Ram 2500","year":2003,"color":"Yellow","stolen":"Never"},
{"id":54,"make":"Hummer","model":"H2","year":2005,"color":"Purple","stolen":"Seldom"},
{"id":55,"make":"Dodge","model":"Viper","year":1997,"color":"Fuscia","stolen":"Seldom"},
{"id":56,"make":"Rolls-Royce","model":"Phantom","year":2011,"color":"Green","stolen":"Once"},
{"id":57,"make":"Saturn","model":"Astra","year":2008,"color":"Blue","stolen":"Once"},
{"id":58,"make":"Chrysler","model":"Town & Country","year":1994,"color":"Mauv","stolen":"Never"},
{"id":59,"make":"Jeep","model":"Comanche","year":1992,"color":"Khaki","stolen":"Weekly"},
{"id":60,"make":"Mercedes-Benz","model":"300SL","year":1992,"color":"Purple","stolen":"Once"},
{"id":61,"make":"Lamborghini","model":"Murciélago","year":2003,"color":"Mauv","stolen":"Once"},
{"id":62,"make":"Spyker","model":"C8 Spyder","year":2004,"color":"Green","stolen":"Monthly"},
{"id":63,"make":"Audi","model":"5000CS","year":1987,"color":"Blue","stolen":"Never"},
{"id":64,"make":"BMW","model":"M5","year":2002,"color":"Yellow","stolen":"Often"},
{"id":65,"make":"BMW","model":"X6","year":2011,"color":"Yellow","stolen":"Weekly"},
{"id":66,"make":"Saturn","model":"Ion","year":2007,"color":"Pink","stolen":"Yearly"},
{"id":67,"make":"Toyota","model":"Matrix","year":2004,"color":"Blue","stolen":"Yearly"},
{"id":68,"make":"Dodge","model":"Caliber","year":2007,"color":"Yellow","stolen":"Seldom"},
{"id":69,"make":"Mercedes-Benz","model":"SL-Class","year":2012,"color":"Khaki","stolen":"Once"},
{"id":70,"make":"Mercedes-Benz","model":"CL-Class","year":2005,"color":"Khaki","stolen":"Seldom"},
{"id":71,"make":"Saab","model":"9-3","year":2010,"color":"Violet","stolen":"Weekly"},
{"id":72,"make":"Chevrolet","model":"Corvette","year":2004,"color":"Goldenrod","stolen":"Weekly"},
{"id":73,"make":"Mazda","model":"B-Series","year":1995,"color":"Teal","stolen":"Often"},
{"id":74,"make":"Cadillac","model":"CTS-V","year":2010,"color":"Khaki","stolen":"Weekly"},
{"id":75,"make":"Buick","model":"Skylark","year":1989,"color":"Violet","stolen":"Seldom"},
{"id":76,"make":"Isuzu","model":"Axiom","year":2002,"color":"Aquamarine","stolen":"Monthly"},
{"id":77,"make":"Volvo","model":"S80","year":2000,"color":"Teal","stolen":"Once"},
{"id":78,"make":"Lincoln","model":"MKZ","year":2007,"color":"Turquoise","stolen":"Never"},
{"id":79,"make":"Chevrolet","model":"Silverado 3500HD","year":2006,"color":"Turquoise","stolen":"Never"},
{"id":80,"make":"Chevrolet","model":"Silverado 2500","year":2011,"color":"Turquoise","stolen":"Once"},
{"id":81,"make":"Ford","model":"F150","year":2012,"color":"Orange","stolen":"Never"},
{"id":82,"make":"Ford","model":"Edge","year":2012,"color":"Violet","stolen":"Yearly"},
{"id":83,"make":"Lincoln","model":"Navigator L","year":2010,"color":"Puce","stolen":"Weekly"},
{"id":84,"make":"Chrysler","model":"Aspen","year":2007,"color":"Teal","stolen":"Once"},
{"id":85,"make":"Isuzu","model":"Ascender","year":2005,"color":"Khaki","stolen":"Seldom"},
{"id":86,"make":"Jaguar","model":"XJ","year":2009,"color":"Yellow","stolen":"Daily"},
{"id":87,"make":"Infiniti","model":"G","year":2001,"color":"Maroon","stolen":"Often"},
{"id":88,"make":"BMW","model":"X5","year":2004,"color":"Green","stolen":"Never"},
{"id":89,"make":"Chevrolet","model":"Tracker","year":1998,"color":"Mauv","stolen":"Once"},
{"id":90,"make":"Volvo","model":"S80","year":2011,"color":"Orange","stolen":"Never"},
{"id":91,"make":"Volkswagen","model":"Cabriolet","year":1989,"color":"Blue","stolen":"Monthly"},
{"id":92,"make":"Acura","model":"MDX","year":2012,"color":"Pink","stolen":"Monthly"},
{"id":93,"make":"Pontiac","model":"G5","year":2008,"color":"Violet","stolen":"Weekly"},
{"id":94,"make":"Dodge","model":"Charger","year":2010,"color":"Yellow","stolen":"Often"},
{"id":95,"make":"Land Rover","model":"LR2","year":2009,"color":"Indigo","stolen":"Yearly"},
{"id":96,"make":"Volkswagen","model":"Scirocco","year":1984,"color":"Aquamarine","stolen":"Never"},
{"id":97,"make":"Volvo","model":"XC90","year":2012,"color":"Indigo","stolen":"Monthly"},
{"id":98,"make":"Mitsubishi","model":"Galant","year":1988,"color":"Orange","stolen":"Weekly"},
{"id":99,"make":"Subaru","model":"XT","year":1985,"color":"Aquamarine","stolen":"Often"},
{"id":100,"make":"Ford","model":"F150","year":1999,"color":"Goldenrod","stolen":"Monthly"},
{"id":101,"make":"Pontiac","model":"Bonneville","year":2003,"color":"Indigo","stolen":"Daily"},
{"id":102,"make":"Lincoln","model":"Continental","year":1989,"color":"Purple","stolen":"Never"},
{"id":103,"make":"Plymouth","model":"Grand Voyager","year":1994,"color":"Khaki","stolen":"Daily"},
{"id":104,"make":"Mitsubishi","model":"Cordia","year":1986,"color":"Pink","stolen":"Once"},
{"id":105,"make":"GMC","model":"Safari","year":1998,"color":"Orange","stolen":"Never"},
{"id":106,"make":"Isuzu","model":"Amigo","year":1998,"color":"Purple","stolen":"Once"},
{"id":107,"make":"Cadillac","model":"Eldorado","year":1994,"color":"Crimson","stolen":"Yearly"},
{"id":108,"make":"Spyker","model":"C8 Laviolette","year":2004,"color":"Fuscia","stolen":"Never"},
{"id":109,"make":"Bentley","model":"Azure","year":2007,"color":"Green","stolen":"Often"},
{"id":110,"make":"Saab","model":"9-3","year":2010,"color":"Yellow","stolen":"Monthly"},
{"id":111,"make":"Ferrari","model":"599 GTB Fiorano","year":2007,"color":"Khaki","stolen":"Weekly"},
{"id":112,"make":"Chevrolet","model":"Sportvan G30","year":1995,"color":"Maroon","stolen":"Weekly"},
{"id":113,"make":"Subaru","model":"Forester","year":1998,"color":"Goldenrod","stolen":"Weekly"},
{"id":114,"make":"Dodge","model":"Stealth","year":1996,"color":"Teal","stolen":"Monthly"},
{"id":115,"make":"Saab","model":"9-5","year":2001,"color":"Khaki","stolen":"Never"},
{"id":116,"make":"Audi","model":"Allroad","year":2001,"color":"Mauv","stolen":"Never"},
{"id":117,"make":"Mazda","model":"323","year":1995,"color":"Khaki","stolen":"Often"},
{"id":118,"make":"Jaguar","model":"XJ","year":2011,"color":"Yellow","stolen":"Daily"},
{"id":119,"make":"Isuzu","model":"Oasis","year":1999,"color":"Pink","stolen":"Never"},
{"id":120,"make":"Oldsmobile","model":"Achieva","year":1994,"color":"Violet","stolen":"Never"},
{"id":121,"make":"Ram","model":"2500","year":2012,"color":"Turquoise","stolen":"Monthly"},
{"id":122,"make":"Chevrolet","model":"Silverado","year":2007,"color":"Fuscia","stolen":"Never"},
{"id":123,"make":"Infiniti","model":"IPL G","year":2011,"color":"Goldenrod","stolen":"Yearly"},
{"id":124,"make":"Mercury","model":"Grand Marquis","year":2006,"color":"Crimson","stolen":"Once"},
{"id":125,"make":"Mercedes-Benz","model":"SL-Class","year":2012,"color":"Puce","stolen":"Weekly"},
{"id":126,"make":"Ford","model":"Windstar","year":2003,"color":"Green","stolen":"Never"},
{"id":127,"make":"Chevrolet","model":"Impala SS","year":1995,"color":"Violet","stolen":"Often"},
{"id":128,"make":"Geo","model":"Prizm","year":1995,"color":"Mauv","stolen":"Once"},
{"id":129,"make":"Infiniti","model":"I","year":2004,"color":"Crimson","stolen":"Never"},
{"id":130,"make":"Buick","model":"Regal","year":2012,"color":"Khaki","stolen":"Monthly"},
{"id":131,"make":"Volkswagen","model":"Eurovan","year":1997,"color":"Puce","stolen":"Never"},
{"id":132,"make":"GMC","model":"Suburban 2500","year":1993,"color":"Maroon","stolen":"Once"},
{"id":133,"make":"Porsche","model":"Cayman","year":2006,"color":"Turquoise","stolen":"Weekly"},
{"id":134,"make":"Lamborghini","model":"Murciélago","year":2004,"color":"Indigo","stolen":"Often"},
{"id":135,"make":"Mazda","model":"Mazdaspeed 3","year":2008,"color":"Maroon","stolen":"Daily"},
{"id":136,"make":"Isuzu","model":"i-290","year":2008,"color":"Fuscia","stolen":"Weekly"},
{"id":137,"make":"Acura","model":"RDX","year":2012,"color":"Teal","stolen":"Monthly"},
{"id":138,"make":"Chevrolet","model":"Suburban 1500","year":1995,"color":"Goldenrod","stolen":"Monthly"},
{"id":139,"make":"Chevrolet","model":"Blazer","year":2003,"color":"Green","stolen":"Yearly"},
{"id":140,"make":"Aston Martin","model":"Vantage","year":2007,"color":"Fuscia","stolen":"Yearly"},
{"id":141,"make":"Volkswagen","model":"Passat","year":1992,"color":"Crimson","stolen":"Weekly"},
{"id":142,"make":"Ford","model":"F250","year":1992,"color":"Crimson","stolen":"Seldom"},
{"id":143,"make":"Chrysler","model":"Concorde","year":1994,"color":"Teal","stolen":"Seldom"},
{"id":144,"make":"Chevrolet","model":"Silverado 1500","year":2001,"color":"Indigo","stolen":"Often"},
{"id":145,"make":"Audi","model":"Quattro","year":1993,"color":"Yellow","stolen":"Monthly"},
{"id":146,"make":"Lexus","model":"RX","year":2001,"color":"Blue","stolen":"Once"},
{"id":147,"make":"Dodge","model":"Grand Caravan","year":1995,"color":"Maroon","stolen":"Daily"},
{"id":148,"make":"Toyota","model":"Land Cruiser","year":2000,"color":"Purple","stolen":"Seldom"},
{"id":149,"make":"Lincoln","model":"Navigator","year":2003,"color":"Teal","stolen":"Seldom"},
{"id":150,"make":"Mitsubishi","model":"Outlander Sport","year":2011,"color":"Purple","stolen":"Never"},
{"id":151,"make":"Nissan","model":"240SX","year":1997,"color":"Pink","stolen":"Daily"},
{"id":152,"make":"Mazda","model":"929","year":1995,"color":"Crimson","stolen":"Never"},
{"id":153,"make":"GMC","model":"Yukon XL 2500","year":2001,"color":"Indigo","stolen":"Daily"},
{"id":154,"make":"Infiniti","model":"G37","year":2009,"color":"Violet","stolen":"Seldom"},
{"id":155,"make":"Pontiac","model":"Trans Sport","year":1990,"color":"Crimson","stolen":"Seldom"},
{"id":156,"make":"Buick","model":"Estate","year":1990,"color":"Maroon","stolen":"Monthly"},
{"id":157,"make":"Dodge","model":"Viper","year":2008,"color":"Violet","stolen":"Monthly"},
{"id":158,"make":"Toyota","model":"Tercel","year":1994,"color":"Indigo","stolen":"Daily"},
{"id":159,"make":"Dodge","model":"Ram Van B250","year":1994,"color":"Violet","stolen":"Once"},
{"id":160,"make":"Mitsubishi","model":"Chariot","year":1995,"color":"Violet","stolen":"Often"},
{"id":161,"make":"Aston Martin","model":"V8 Vantage","year":2011,"color":"Yellow","stolen":"Daily"},
{"id":162,"make":"Ford","model":"F-Series","year":1991,"color":"Indigo","stolen":"Never"},
{"id":163,"make":"Ford","model":"Edge","year":2007,"color":"Goldenrod","stolen":"Weekly"},
{"id":164,"make":"Ford","model":"E250","year":2009,"color":"Puce","stolen":"Daily"},
{"id":165,"make":"Volkswagen","model":"Jetta","year":2007,"color":"Mauv","stolen":"Seldom"},
{"id":166,"make":"Plymouth","model":"Neon","year":1999,"color":"Fuscia","stolen":"Often"},
{"id":167,"make":"Nissan","model":"Pathfinder","year":2010,"color":"Maroon","stolen":"Often"},
{"id":168,"make":"Kia","model":"Sephia","year":1999,"color":"Maroon","stolen":"Never"},
{"id":169,"make":"Hyundai","model":"Tiburon","year":1998,"color":"Aquamarine","stolen":"Never"},
{"id":170,"make":"Pontiac","model":"6000","year":1988,"color":"Maroon","stolen":"Seldom"},
{"id":171,"make":"Chevrolet","model":"Express 3500","year":2002,"color":"Fuscia","stolen":"Often"},
{"id":172,"make":"Chevrolet","model":"Corvette","year":1960,"color":"Orange","stolen":"Often"},
{"id":173,"make":"Mazda","model":"626","year":1996,"color":"Goldenrod","stolen":"Yearly"},
{"id":174,"make":"BMW","model":"3 Series","year":1994,"color":"Violet","stolen":"Daily"},
{"id":175,"make":"Mercedes-Benz","model":"CL-Class","year":2008,"color":"Violet","stolen":"Often"},
{"id":176,"make":"Mercedes-Benz","model":"CL-Class","year":1998,"color":"Crimson","stolen":"Yearly"},
{"id":177,"make":"Subaru","model":"Loyale","year":1993,"color":"Crimson","stolen":"Never"},
{"id":178,"make":"Cadillac","model":"Fleetwood","year":1995,"color":"Khaki","stolen":"Monthly"},
{"id":179,"make":"Lexus","model":"LS","year":2003,"color":"Maroon","stolen":"Weekly"},
{"id":180,"make":"Mercedes-Benz","model":"600SL","year":1993,"color":"Indigo","stolen":"Never"},
{"id":181,"make":"Lexus","model":"CT","year":2012,"color":"Mauv","stolen":"Yearly"},
{"id":182,"make":"Porsche","model":"Boxster","year":2003,"color":"Blue","stolen":"Monthly"},
{"id":183,"make":"Mitsubishi","model":"Pajero","year":1994,"color":"Purple","stolen":"Yearly"},
{"id":184,"make":"Mercedes-Benz","model":"C-Class","year":2006,"color":"Violet","stolen":"Yearly"},
{"id":185,"make":"Jeep","model":"Patriot","year":2008,"color":"Green","stolen":"Daily"},
{"id":186,"make":"Lotus","model":"Esprit","year":1995,"color":"Yellow","stolen":"Often"},
{"id":187,"make":"Pontiac","model":"Solstice","year":2006,"color":"Orange","stolen":"Often"},
{"id":188,"make":"Chevrolet","model":"Corvette","year":1975,"color":"Maroon","stolen":"Seldom"},
{"id":189,"make":"Mitsubishi","model":"Chariot","year":1995,"color":"Red","stolen":"Yearly"},
{"id":190,"make":"Dodge","model":"Ram 2500 Club","year":1996,"color":"Purple","stolen":"Monthly"},
{"id":191,"make":"Mazda","model":"Miata MX-5","year":1999,"color":"Teal","stolen":"Daily"},
{"id":192,"make":"BMW","model":"X5 M","year":2013,"color":"Puce","stolen":"Daily"},
{"id":193,"make":"Hyundai","model":"Veracruz","year":2009,"color":"Blue","stolen":"Weekly"},
{"id":194,"make":"GMC","model":"Savana 2500","year":2008,"color":"Yellow","stolen":"Never"},
{"id":195,"make":"GMC","model":"Envoy","year":2004,"color":"Red","stolen":"Often"},
{"id":196,"make":"Dodge","model":"Stratus","year":2006,"color":"Puce","stolen":"Daily"},
{"id":197,"make":"BMW","model":"X5","year":2009,"color":"Puce","stolen":"Often"},
{"id":198,"make":"BMW","model":"3 Series","year":1999,"color":"Purple","stolen":"Often"},
{"id":199,"make":"Daewoo","model":"Nubira","year":1999,"color":"Green","stolen":"Yearly"},
{"id":200,"make":"Pontiac","model":"Tempest","year":1966,"color":"Puce","stolen":"Monthly"},
{"id":201,"make":"Chevrolet","model":"Camaro","year":1995,"color":"Orange","stolen":"Often"},
{"id":202,"make":"Mazda","model":"MX-5","year":2003,"color":"Mauv","stolen":"Seldom"},
{"id":203,"make":"Buick","model":"LeSabre","year":1987,"color":"Orange","stolen":"Once"},
{"id":204,"make":"Oldsmobile","model":"Aurora","year":1998,"color":"Blue","stolen":"Monthly"},
{"id":205,"make":"Volkswagen","model":"Golf III","year":1994,"color":"Violet","stolen":"Daily"},
{"id":206,"make":"Lincoln","model":"Continental","year":1986,"color":"Green","stolen":"Daily"},
{"id":207,"make":"Infiniti","model":"Q","year":1995,"color":"Khaki","stolen":"Yearly"},
{"id":208,"make":"Audi","model":"4000CS Quattro","year":1986,"color":"Indigo","stolen":"Once"},
{"id":209,"make":"Suzuki","model":"Sidekick","year":1990,"color":"Puce","stolen":"Daily"},
{"id":210,"make":"Oldsmobile","model":"88","year":1994,"color":"Purple","stolen":"Yearly"},
{"id":211,"make":"Plymouth","model":"Colt Vista","year":1993,"color":"Fuscia","stolen":"Once"},
{"id":212,"make":"Jeep","model":"Wrangler","year":1998,"color":"Purple","stolen":"Seldom"},
{"id":213,"make":"Suzuki","model":"Swift","year":2000,"color":"Blue","stolen":"Daily"},
{"id":214,"make":"GMC","model":"Yukon XL 1500","year":2010,"color":"Violet","stolen":"Often"},
{"id":215,"make":"Aptera","model":"Typ-1","year":2008,"color":"Aquamarine","stolen":"Daily"},
{"id":216,"make":"Hummer","model":"H2 SUV","year":2006,"color":"Red","stolen":"Often"},
{"id":217,"make":"Honda","model":"Fit","year":2012,"color":"Goldenrod","stolen":"Monthly"},
{"id":218,"make":"Mercury","model":"Villager","year":1995,"color":"Teal","stolen":"Seldom"},
{"id":219,"make":"Ford","model":"Transit Connect","year":2011,"color":"Puce","stolen":"Seldom"},
{"id":220,"make":"Ford","model":"Contour","year":1997,"color":"Violet","stolen":"Once"},
{"id":221,"make":"Chevrolet","model":"Caprice","year":1995,"color":"Aquamarine","stolen":"Weekly"},
{"id":222,"make":"Land Rover","model":"Discovery","year":2001,"color":"Turquoise","stolen":"Yearly"},
{"id":223,"make":"Land Rover","model":"LR2","year":2010,"color":"Yellow","stolen":"Often"},
{"id":224,"make":"Oldsmobile","model":"Aurora","year":1998,"color":"Fuscia","stolen":"Weekly"},
{"id":225,"make":"GMC","model":"Envoy","year":2005,"color":"Orange","stolen":"Monthly"},
{"id":226,"make":"Ford","model":"E150","year":2006,"color":"Crimson","stolen":"Never"},
{"id":227,"make":"Mazda","model":"B2000","year":1985,"color":"Teal","stolen":"Weekly"},
{"id":228,"make":"Maserati","model":"GranSport","year":2006,"color":"Crimson","stolen":"Never"},
{"id":229,"make":"Ford","model":"Mustang","year":1983,"color":"Maroon","stolen":"Never"},
{"id":230,"make":"Kia","model":"Sephia","year":1999,"color":"Indigo","stolen":"Weekly"},
{"id":231,"make":"Saturn","model":"VUE","year":2003,"color":"Orange","stolen":"Daily"},
{"id":232,"make":"Aston Martin","model":"Vanquish S","year":2006,"color":"Crimson","stolen":"Seldom"},
{"id":233,"make":"Mitsubishi","model":"L300","year":1988,"color":"Fuscia","stolen":"Once"},
{"id":234,"make":"Lexus","model":"RX","year":2003,"color":"Turquoise","stolen":"Once"},
{"id":235,"make":"Kia","model":"Spectra","year":2000,"color":"Mauv","stolen":"Often"},
{"id":236,"make":"Ford","model":"E250","year":2010,"color":"Teal","stolen":"Once"},
{"id":237,"make":"Infiniti","model":"I","year":1997,"color":"Mauv","stolen":"Once"},
{"id":238,"make":"GMC","model":"Savana","year":2010,"color":"Mauv","stolen":"Weekly"},
{"id":239,"make":"Land Rover","model":"LR2","year":2010,"color":"Mauv","stolen":"Often"},
{"id":240,"make":"Audi","model":"Cabriolet","year":1996,"color":"Green","stolen":"Never"},
{"id":241,"make":"Dodge","model":"Ram 3500 Club","year":1997,"color":"Puce","stolen":"Seldom"},
{"id":242,"make":"Honda","model":"Crosstour","year":2012,"color":"Khaki","stolen":"Weekly"},
{"id":243,"make":"Chevrolet","model":"Malibu","year":1998,"color":"Fuscia","stolen":"Never"},
{"id":244,"make":"Oldsmobile","model":"Ciera","year":1996,"color":"Turquoise","stolen":"Never"},
{"id":245,"make":"Cadillac","model":"Seville","year":1999,"color":"Khaki","stolen":"Yearly"},
{"id":246,"make":"Toyota","model":"Paseo","year":1997,"color":"Teal","stolen":"Weekly"},
{"id":247,"make":"Chevrolet","model":"SSR","year":2005,"color":"Goldenrod","stolen":"Daily"},
{"id":248,"make":"Mazda","model":"Mazda6","year":2005,"color":"Red","stolen":"Once"},
{"id":249,"make":"Acura","model":"TL","year":1996,"color":"Blue","stolen":"Daily"},
{"id":250,"make":"Buick","model":"Regal","year":1996,"color":"Crimson","stolen":"Monthly"},
{"id":251,"make":"Geo","model":"Tracker","year":1994,"color":"Green","stolen":"Daily"},
{"id":252,"make":"Saturn","model":"Ion","year":2003,"color":"Khaki","stolen":"Weekly"},
{"id":253,"make":"Lexus","model":"IS F","year":2010,"color":"Purple","stolen":"Yearly"},
{"id":254,"make":"Kia","model":"Forte","year":2011,"color":"Turquoise","stolen":"Once"},
{"id":255,"make":"Lexus","model":"LS","year":2006,"color":"Pink","stolen":"Weekly"},
{"id":256,"make":"Pontiac","model":"GTO","year":1968,"color":"Violet","stolen":"Often"},
{"id":257,"make":"Ford","model":"Windstar","year":2003,"color":"Pink","stolen":"Daily"},
{"id":258,"make":"Toyota","model":"Camry","year":2003,"color":"Goldenrod","stolen":"Never"},
{"id":259,"make":"Mercedes-Benz","model":"GL-Class","year":2009,"color":"Yellow","stolen":"Weekly"},
{"id":260,"make":"Volkswagen","model":"GTI","year":2011,"color":"Maroon","stolen":"Once"},
{"id":261,"make":"Oldsmobile","model":"Achieva","year":1993,"color":"Yellow","stolen":"Seldom"},
{"id":262,"make":"Chevrolet","model":"Express","year":2008,"color":"Violet","stolen":"Yearly"},
{"id":263,"make":"Chevrolet","model":"2500","year":2000,"color":"Yellow","stolen":"Daily"},
{"id":264,"make":"Hyundai","model":"Elantra","year":2001,"color":"Mauv","stolen":"Monthly"},
{"id":265,"make":"Chevrolet","model":"Corvette","year":1965,"color":"Blue","stolen":"Monthly"},
{"id":266,"make":"MINI","model":"Cooper","year":2012,"color":"Indigo","stolen":"Weekly"},
{"id":267,"make":"Mercedes-Benz","model":"GLK-Class","year":2010,"color":"Orange","stolen":"Never"},
{"id":268,"make":"Nissan","model":"Pathfinder","year":1996,"color":"Green","stolen":"Daily"},
{"id":269,"make":"Mitsubishi","model":"Endeavor","year":2007,"color":"Teal","stolen":"Monthly"},
{"id":270,"make":"BMW","model":"M5","year":1993,"color":"Goldenrod","stolen":"Never"},
{"id":271,"make":"Lincoln","model":"Mark VII","year":1992,"color":"Crimson","stolen":"Daily"},
{"id":272,"make":"Honda","model":"Civic","year":2011,"color":"Mauv","stolen":"Never"},
{"id":273,"make":"Honda","model":"Odyssey","year":2007,"color":"Puce","stolen":"Monthly"},
{"id":274,"make":"Chevrolet","model":"Avalanche","year":2011,"color":"Goldenrod","stolen":"Once"},
{"id":275,"make":"Ford","model":"Explorer Sport Trac","year":2007,"color":"Maroon","stolen":"Weekly"},
{"id":276,"make":"Nissan","model":"Cube","year":2010,"color":"Turquoise","stolen":"Often"},
{"id":277,"make":"BMW","model":"X3","year":2004,"color":"Yellow","stolen":"Often"},
{"id":278,"make":"Land Rover","model":"Freelander","year":2009,"color":"Maroon","stolen":"Daily"},
{"id":279,"make":"Mitsubishi","model":"Eclipse","year":1990,"color":"Turquoise","stolen":"Monthly"},
{"id":280,"make":"Mercury","model":"Mountaineer","year":2004,"color":"Yellow","stolen":"Never"},
{"id":281,"make":"Mercedes-Benz","model":"S-Class","year":1991,"color":"Crimson","stolen":"Often"},
{"id":282,"make":"Audi","model":"RS 6","year":2003,"color":"Red","stolen":"Once"},
{"id":283,"make":"Toyota","model":"Matrix","year":2006,"color":"Blue","stolen":"Never"},
{"id":284,"make":"Pontiac","model":"6000","year":1985,"color":"Puce","stolen":"Monthly"},
{"id":285,"make":"GMC","model":"Sierra 2500HD","year":2006,"color":"Khaki","stolen":"Seldom"},
{"id":286,"make":"Mitsubishi","model":"Pajero","year":2006,"color":"Puce","stolen":"Weekly"},
{"id":287,"make":"Pontiac","model":"Trans Sport","year":1997,"color":"Khaki","stolen":"Once"},
{"id":288,"make":"Kia","model":"Amanti","year":2004,"color":"Khaki","stolen":"Yearly"},
{"id":289,"make":"Volvo","model":"XC70","year":2010,"color":"Fuscia","stolen":"Often"},
{"id":290,"make":"Toyota","model":"4Runner","year":2009,"color":"Puce","stolen":"Seldom"},
{"id":291,"make":"Chevrolet","model":"Monte Carlo","year":1995,"color":"Orange","stolen":"Often"},
{"id":292,"make":"Hyundai","model":"Santa Fe","year":2006,"color":"Yellow","stolen":"Once"},
{"id":293,"make":"Jeep","model":"Wrangler","year":2012,"color":"Green","stolen":"Once"},
{"id":294,"make":"Ford","model":"Taurus","year":1989,"color":"Orange","stolen":"Weekly"},
{"id":295,"make":"Ford","model":"F250","year":1993,"color":"Puce","stolen":"Weekly"},
{"id":296,"make":"Jeep","model":"Grand Cherokee","year":1999,"color":"Turquoise","stolen":"Daily"},
{"id":297,"make":"GMC","model":"Yukon","year":2006,"color":"Violet","stolen":"Daily"},
{"id":298,"make":"Porsche","model":"968","year":1994,"color":"Puce","stolen":"Daily"},
{"id":299,"make":"Toyota","model":"Celica","year":1994,"color":"Turquoise","stolen":"Daily"},
{"id":300,"make":"Jeep","model":"Liberty","year":2004,"color":"Pink","stolen":"Monthly"},
{"id":301,"make":"Eagle","model":"Talon","year":1992,"color":"Teal","stolen":"Seldom"},
{"id":302,"make":"Mitsubishi","model":"Diamante","year":2004,"color":"Purple","stolen":"Often"},
{"id":303,"make":"Mercury","model":"Mountaineer","year":1998,"color":"Goldenrod","stolen":"Never"},
{"id":304,"make":"Land Rover","model":"Discovery","year":1994,"color":"Turquoise","stolen":"Once"},
{"id":305,"make":"Oldsmobile","model":"Silhouette","year":1994,"color":"Teal","stolen":"Yearly"},
{"id":306,"make":"Lincoln","model":"MKS","year":2013,"color":"Purple","stolen":"Daily"},
{"id":307,"make":"Volvo","model":"960","year":1995,"color":"Purple","stolen":"Never"},
{"id":308,"make":"Nissan","model":"Maxima","year":2003,"color":"Fuscia","stolen":"Never"},
{"id":309,"make":"Ford","model":"LTD Crown Victoria","year":1993,"color":"Crimson","stolen":"Daily"},
{"id":310,"make":"Toyota","model":"Corolla","year":2007,"color":"Goldenrod","stolen":"Daily"},
{"id":311,"make":"Suzuki","model":"XL7","year":2006,"color":"Red","stolen":"Weekly"},
{"id":312,"make":"Honda","model":"Fit","year":2010,"color":"Green","stolen":"Often"},
{"id":313,"make":"Toyota","model":"Sequoia","year":2011,"color":"Violet","stolen":"Never"},
{"id":314,"make":"Audi","model":"A4","year":1998,"color":"Fuscia","stolen":"Once"},
{"id":315,"make":"Mazda","model":"Mazda6","year":2003,"color":"Red","stolen":"Weekly"},
{"id":316,"make":"Hyundai","model":"Elantra","year":2010,"color":"Goldenrod","stolen":"Monthly"},
{"id":317,"make":"Nissan","model":"Sentra","year":1995,"color":"Goldenrod","stolen":"Monthly"},
{"id":318,"make":"Volvo","model":"V40","year":2001,"color":"Green","stolen":"Never"},
{"id":319,"make":"Chevrolet","model":"Blazer","year":2002,"color":"Puce","stolen":"Once"},
{"id":320,"make":"Volkswagen","model":"Jetta","year":1999,"color":"Khaki","stolen":"Never"},
{"id":321,"make":"Ford","model":"Escape","year":2005,"color":"Pink","stolen":"Seldom"},
{"id":322,"make":"Ford","model":"F-Series","year":1992,"color":"Violet","stolen":"Seldom"},
{"id":323,"make":"Chevrolet","model":"Venture","year":2000,"color":"Orange","stolen":"Never"},
{"id":324,"make":"Lincoln","model":"MKS","year":2009,"color":"Pink","stolen":"Weekly"},
{"id":325,"make":"Toyota","model":"Tacoma Xtra","year":2004,"color":"Aquamarine","stolen":"Once"},
{"id":326,"make":"BMW","model":"M5","year":2009,"color":"Khaki","stolen":"Yearly"},
{"id":327,"make":"Kia","model":"Sedona","year":2009,"color":"Pink","stolen":"Often"},
{"id":328,"make":"Porsche","model":"Cayman","year":2012,"color":"Puce","stolen":"Once"},
{"id":329,"make":"Audi","model":"5000S","year":1984,"color":"Teal","stolen":"Seldom"},
{"id":330,"make":"Cadillac","model":"Seville","year":1993,"color":"Yellow","stolen":"Seldom"},
{"id":331,"make":"Honda","model":"del Sol","year":1996,"color":"Fuscia","stolen":"Yearly"},
{"id":332,"make":"Kia","model":"Rio","year":2003,"color":"Goldenrod","stolen":"Yearly"},
{"id":333,"make":"Toyota","model":"RAV4","year":2005,"color":"Green","stolen":"Once"},
{"id":334,"make":"Porsche","model":"914","year":1970,"color":"Teal","stolen":"Monthly"},
{"id":335,"make":"Volkswagen","model":"Rabbit","year":2009,"color":"Red","stolen":"Never"},
{"id":336,"make":"Lincoln","model":"Continental","year":1997,"color":"Orange","stolen":"Daily"},
{"id":337,"make":"Ford","model":"Bronco II","year":1985,"color":"Orange","stolen":"Yearly"},
{"id":338,"make":"Mitsubishi","model":"Galant","year":2002,"color":"Puce","stolen":"Once"},
{"id":339,"make":"Hyundai","model":"Genesis Coupe","year":2011,"color":"Indigo","stolen":"Weekly"},
{"id":340,"make":"Volkswagen","model":"New Beetle","year":2004,"color":"Indigo","stolen":"Often"},
{"id":341,"make":"Mercedes-Benz","model":"S-Class","year":1984,"color":"Aquamarine","stolen":"Yearly"},
{"id":342,"make":"Pontiac","model":"Turbo Firefly","year":1990,"color":"Orange","stolen":"Yearly"},
{"id":343,"make":"Isuzu","model":"Trooper","year":1993,"color":"Crimson","stolen":"Often"},
{"id":344,"make":"Kia","model":"Optima","year":2010,"color":"Orange","stolen":"Weekly"},
{"id":345,"make":"Infiniti","model":"EX","year":2012,"color":"Maroon","stolen":"Once"},
{"id":346,"make":"Chevrolet","model":"Suburban 2500","year":1995,"color":"Red","stolen":"Once"},
{"id":347,"make":"Buick","model":"Regal","year":1987,"color":"Violet","stolen":"Never"},
{"id":348,"make":"Maybach","model":"57","year":2006,"color":"Fuscia","stolen":"Never"},
{"id":349,"make":"GMC","model":"Sonoma","year":2002,"color":"Green","stolen":"Daily"},
{"id":350,"make":"Pontiac","model":"Grand Prix","year":1993,"color":"Orange","stolen":"Weekly"},
{"id":351,"make":"Volkswagen","model":"Golf","year":1999,"color":"Violet","stolen":"Once"},
{"id":352,"make":"Chevrolet","model":"Aveo","year":2009,"color":"Blue","stolen":"Monthly"},
{"id":353,"make":"Oldsmobile","model":"Achieva","year":1994,"color":"Teal","stolen":"Yearly"},
{"id":354,"make":"Mitsubishi","model":"Raider","year":2006,"color":"Purple","stolen":"Never"},
{"id":355,"make":"Mercedes-Benz","model":"E-Class","year":1987,"color":"Violet","stolen":"Weekly"},
{"id":356,"make":"Ford","model":"Aerostar","year":1988,"color":"Violet","stolen":"Once"},
{"id":357,"make":"Mercedes-Benz","model":"W126","year":1983,"color":"Orange","stolen":"Weekly"},
{"id":358,"make":"Dodge","model":"Ram Van 2500","year":2000,"color":"Yellow","stolen":"Seldom"},
{"id":359,"make":"Acura","model":"TL","year":1999,"color":"Khaki","stolen":"Seldom"},
{"id":360,"make":"Toyota","model":"Camry","year":2009,"color":"Khaki","stolen":"Never"},
{"id":361,"make":"GMC","model":"Yukon","year":1994,"color":"Red","stolen":"Seldom"},
{"id":362,"make":"Isuzu","model":"Ascender","year":2006,"color":"Khaki","stolen":"Often"},
{"id":363,"make":"BMW","model":"3 Series","year":1995,"color":"Puce","stolen":"Monthly"},
{"id":364,"make":"Isuzu","model":"Ascender","year":2004,"color":"Teal","stolen":"Monthly"},
{"id":365,"make":"Mazda","model":"MX-3","year":1993,"color":"Blue","stolen":"Weekly"},
{"id":366,"make":"Infiniti","model":"M","year":2011,"color":"Orange","stolen":"Never"},
{"id":367,"make":"Nissan","model":"Murano","year":2010,"color":"Red","stolen":"Never"},
{"id":368,"make":"Ford","model":"Taurus","year":2001,"color":"Mauv","stolen":"Yearly"},
{"id":369,"make":"Bentley","model":"Continental GTC","year":2008,"color":"Indigo","stolen":"Never"},
{"id":370,"make":"Chevrolet","model":"Tracker","year":2004,"color":"Yellow","stolen":"Never"},
{"id":371,"make":"Dodge","model":"Dakota Club","year":2003,"color":"Aquamarine","stolen":"Yearly"},
{"id":372,"make":"Lexus","model":"ES","year":1998,"color":"Indigo","stolen":"Seldom"},
{"id":373,"make":"Porsche","model":"Cayenne","year":2008,"color":"Puce","stolen":"Weekly"},
{"id":374,"make":"Ford","model":"F350","year":2003,"color":"Pink","stolen":"Once"},
{"id":375,"make":"Mercury","model":"Mystique","year":2000,"color":"Maroon","stolen":"Never"},
{"id":376,"make":"Ford","model":"E250","year":2009,"color":"Turquoise","stolen":"Once"},
{"id":377,"make":"Mitsubishi","model":"Lancer Evolution","year":2004,"color":"Orange","stolen":"Once"},
{"id":378,"make":"Land Rover","model":"Discovery","year":2005,"color":"Pink","stolen":"Once"},
{"id":379,"make":"Toyota","model":"4Runner","year":2005,"color":"Green","stolen":"Seldom"},
{"id":380,"make":"Land Rover","model":"LR3","year":2007,"color":"Goldenrod","stolen":"Often"},
{"id":381,"make":"GMC","model":"1500 Club Coupe","year":1998,"color":"Khaki","stolen":"Often"},
{"id":382,"make":"Mercury","model":"Grand Marquis","year":2011,"color":"Maroon","stolen":"Yearly"},
{"id":383,"make":"Chevrolet","model":"Astro","year":1992,"color":"Khaki","stolen":"Often"},
{"id":384,"make":"Dodge","model":"Intrepid","year":1998,"color":"Aquamarine","stolen":"Never"},
{"id":385,"make":"Saturn","model":"Relay","year":2006,"color":"Green","stolen":"Yearly"},
{"id":386,"make":"Nissan","model":"370Z","year":2011,"color":"Goldenrod","stolen":"Often"},
{"id":387,"make":"Ford","model":"Tempo","year":1994,"color":"Purple","stolen":"Never"},
{"id":388,"make":"Toyota","model":"Camry","year":1998,"color":"Pink","stolen":"Monthly"},
{"id":389,"make":"Chevrolet","model":"Express 3500","year":2003,"color":"Orange","stolen":"Daily"},
{"id":390,"make":"Audi","model":"A8","year":2010,"color":"Turquoise","stolen":"Daily"},
{"id":391,"make":"Kia","model":"Sephia","year":2001,"color":"Pink","stolen":"Often"},
{"id":392,"make":"Dodge","model":"Dakota Club","year":2002,"color":"Green","stolen":"Yearly"},
{"id":393,"make":"Oldsmobile","model":"Aurora","year":2001,"color":"Green","stolen":"Seldom"},
{"id":394,"make":"Volvo","model":"V50","year":2006,"color":"Turquoise","stolen":"Seldom"},
{"id":395,"make":"Volvo","model":"V40","year":2002,"color":"Yellow","stolen":"Seldom"},
{"id":396,"make":"Chevrolet","model":"Silverado 3500","year":2009,"color":"Yellow","stolen":"Often"},
{"id":397,"make":"Nissan","model":"Sentra","year":2005,"color":"Aquamarine","stolen":"Seldom"},
{"id":398,"make":"Dodge","model":"Dakota","year":2003,"color":"Crimson","stolen":"Once"},
{"id":399,"make":"Chevrolet","model":"Lumina","year":2000,"color":"Purple","stolen":"Weekly"},
{"id":400,"make":"Pontiac","model":"Firefly","year":1990,"color":"Pink","stolen":"Yearly"},
{"id":401,"make":"Audi","model":"S4","year":2009,"color":"Red","stolen":"Never"},
{"id":402,"make":"Lincoln","model":"MKX","year":2012,"color":"Purple","stolen":"Once"},
{"id":403,"make":"Buick","model":"LaCrosse","year":2009,"color":"Yellow","stolen":"Yearly"},
{"id":404,"make":"Toyota","model":"MR2","year":1994,"color":"Pink","stolen":"Monthly"},
{"id":405,"make":"Mazda","model":"MX-5","year":1991,"color":"Khaki","stolen":"Weekly"},
{"id":406,"make":"Aston Martin","model":"Rapide","year":2010,"color":"Khaki","stolen":"Daily"},
{"id":407,"make":"Buick","model":"Regal","year":1986,"color":"Mauv","stolen":"Never"},
{"id":408,"make":"Honda","model":"S2000","year":2000,"color":"Indigo","stolen":"Yearly"},
{"id":409,"make":"Chevrolet","model":"2500","year":2000,"color":"Green","stolen":"Once"},
{"id":410,"make":"Nissan","model":"Xterra","year":2004,"color":"Yellow","stolen":"Weekly"},
{"id":411,"make":"GMC","model":"Envoy","year":1999,"color":"Pink","stolen":"Yearly"},
{"id":412,"make":"Dodge","model":"Ram 50","year":1992,"color":"Turquoise","stolen":"Weekly"},
{"id":413,"make":"Ferrari","model":"458 Italia","year":2010,"color":"Green","stolen":"Often"},
{"id":414,"make":"Lincoln","model":"Town Car","year":2008,"color":"Crimson","stolen":"Daily"},
{"id":415,"make":"Pontiac","model":"Firebird","year":1997,"color":"Fuscia","stolen":"Once"},
{"id":416,"make":"Chevrolet","model":"Blazer","year":2004,"color":"Blue","stolen":"Often"},
{"id":417,"make":"Cadillac","model":"Seville","year":2001,"color":"Khaki","stolen":"Daily"},
{"id":418,"make":"GMC","model":"Envoy XL","year":2005,"color":"Maroon","stolen":"Weekly"},
{"id":419,"make":"Aston Martin","model":"V8 Vantage","year":2006,"color":"Blue","stolen":"Daily"},
{"id":420,"make":"Lincoln","model":"Mark VII","year":1984,"color":"Mauv","stolen":"Once"},
{"id":421,"make":"Mercury","model":"Villager","year":1993,"color":"Violet","stolen":"Often"},
{"id":422,"make":"Buick","model":"Regal","year":2004,"color":"Khaki","stolen":"Daily"},
{"id":423,"make":"Chevrolet","model":"Silverado 1500","year":2002,"color":"Purple","stolen":"Daily"},
{"id":424,"make":"Mercedes-Benz","model":"SL-Class","year":2005,"color":"Pink","stolen":"Yearly"},
{"id":425,"make":"Pontiac","model":"Grand Prix","year":1963,"color":"Fuscia","stolen":"Often"},
{"id":426,"make":"Cadillac","model":"Seville","year":2002,"color":"Pink","stolen":"Weekly"},
{"id":427,"make":"Nissan","model":"Pathfinder","year":1996,"color":"Puce","stolen":"Once"},
{"id":428,"make":"Mazda","model":"B2000","year":1985,"color":"Aquamarine","stolen":"Yearly"},
{"id":429,"make":"Infiniti","model":"I","year":1996,"color":"Mauv","stolen":"Once"},
{"id":430,"make":"Honda","model":"Civic","year":1992,"color":"Turquoise","stolen":"Once"},
{"id":431,"make":"Buick","model":"Park Avenue","year":2001,"color":"Maroon","stolen":"Monthly"},
{"id":432,"make":"Chevrolet","model":"Blazer","year":2003,"color":"Maroon","stolen":"Weekly"},
{"id":433,"make":"Honda","model":"Element","year":2006,"color":"Purple","stolen":"Once"},
{"id":434,"make":"Nissan","model":"300ZX","year":1991,"color":"Violet","stolen":"Seldom"},
{"id":435,"make":"Ford","model":"Windstar","year":1998,"color":"Orange","stolen":"Seldom"},
{"id":436,"make":"Mazda","model":"323","year":1994,"color":"Maroon","stolen":"Often"},
{"id":437,"make":"Saab","model":"9000","year":1989,"color":"Pink","stolen":"Yearly"},
{"id":438,"make":"Chevrolet","model":"Monte Carlo","year":2003,"color":"Indigo","stolen":"Monthly"},
{"id":439,"make":"Ford","model":"Explorer","year":2011,"color":"Yellow","stolen":"Yearly"},
{"id":440,"make":"Buick","model":"Terraza","year":2006,"color":"Red","stolen":"Seldom"},
{"id":441,"make":"Buick","model":"Roadmaster","year":1991,"color":"Fuscia","stolen":"Daily"},
{"id":442,"make":"Hyundai","model":"Accent","year":2005,"color":"Indigo","stolen":"Once"},
{"id":443,"make":"Chrysler","model":"Town & Country","year":2002,"color":"Pink","stolen":"Yearly"},
{"id":444,"make":"Chevrolet","model":"Avalanche 2500","year":2002,"color":"Yellow","stolen":"Never"},
{"id":445,"make":"Mercedes-Benz","model":"190E","year":1993,"color":"Yellow","stolen":"Weekly"},
{"id":446,"make":"Morgan","model":"Aero 8","year":2008,"color":"Green","stolen":"Once"},
{"id":447,"make":"Mercedes-Benz","model":"SL-Class","year":1990,"color":"Blue","stolen":"Often"},
{"id":448,"make":"Geo","model":"Tracker","year":1995,"color":"Pink","stolen":"Once"},
{"id":449,"make":"Mazda","model":"RX-7","year":1985,"color":"Teal","stolen":"Daily"},
{"id":450,"make":"Ford","model":"Fairlane","year":1966,"color":"Turquoise","stolen":"Yearly"},
{"id":451,"make":"Chevrolet","model":"Aveo","year":2006,"color":"Aquamarine","stolen":"Daily"},
{"id":452,"make":"Volkswagen","model":"Type 2","year":1990,"color":"Mauv","stolen":"Monthly"},
{"id":453,"make":"Lexus","model":"GS","year":2000,"color":"Purple","stolen":"Weekly"},
{"id":454,"make":"Ford","model":"F350","year":2005,"color":"Mauv","stolen":"Weekly"},
{"id":455,"make":"Chevrolet","model":"Avalanche 2500","year":2006,"color":"Puce","stolen":"Once"},
{"id":456,"make":"Pontiac","model":"Grand Prix","year":1962,"color":"Red","stolen":"Daily"},
{"id":457,"make":"Infiniti","model":"G","year":2005,"color":"Goldenrod","stolen":"Weekly"},
{"id":458,"make":"Honda","model":"CR-X","year":1985,"color":"Purple","stolen":"Daily"},
{"id":459,"make":"Buick","model":"Estate","year":1990,"color":"Aquamarine","stolen":"Once"},
{"id":460,"make":"Chevrolet","model":"Suburban 1500","year":1996,"color":"Orange","stolen":"Monthly"},
{"id":461,"make":"BMW","model":"Z4 M Roadster","year":2009,"color":"Green","stolen":"Never"},
{"id":462,"make":"Volvo","model":"C70","year":1999,"color":"Turquoise","stolen":"Monthly"},
{"id":463,"make":"Scion","model":"xA","year":2005,"color":"Orange","stolen":"Weekly"},
{"id":464,"make":"Volkswagen","model":"GTI","year":1992,"color":"Puce","stolen":"Once"},
{"id":465,"make":"Oldsmobile","model":"Alero","year":2002,"color":"Indigo","stolen":"Yearly"},
{"id":466,"make":"Lincoln","model":"Navigator L","year":2012,"color":"Pink","stolen":"Monthly"},
{"id":467,"make":"Chevrolet","model":"Express 3500","year":2003,"color":"Yellow","stolen":"Weekly"},
{"id":468,"make":"Ford","model":"Explorer","year":1999,"color":"Green","stolen":"Daily"},
{"id":469,"make":"Subaru","model":"Impreza","year":2001,"color":"Yellow","stolen":"Often"},
{"id":470,"make":"Acura","model":"RSX","year":2003,"color":"Blue","stolen":"Often"},
{"id":471,"make":"Volvo","model":"C30","year":2008,"color":"Maroon","stolen":"Never"},
{"id":472,"make":"Chevrolet","model":"Caprice","year":1996,"color":"Khaki","stolen":"Monthly"},
{"id":473,"make":"Volkswagen","model":"Cabriolet","year":1996,"color":"Violet","stolen":"Seldom"},
{"id":474,"make":"Volkswagen","model":"Jetta","year":1990,"color":"Blue","stolen":"Often"},
{"id":475,"make":"Bugatti","model":"Veyron","year":2009,"color":"Turquoise","stolen":"Seldom"},
{"id":476,"make":"Scion","model":"xD","year":2011,"color":"Orange","stolen":"Seldom"},
{"id":477,"make":"GMC","model":"Sierra 3500","year":2007,"color":"Goldenrod","stolen":"Daily"},
{"id":478,"make":"Pontiac","model":"Firebird","year":1968,"color":"Yellow","stolen":"Daily"},
{"id":479,"make":"Pontiac","model":"Daewoo Kalos","year":2006,"color":"Puce","stolen":"Daily"},
{"id":480,"make":"Chevrolet","model":"Astro","year":2000,"color":"Puce","stolen":"Daily"},
{"id":481,"make":"Subaru","model":"Loyale","year":1990,"color":"Fuscia","stolen":"Never"},
{"id":482,"make":"GMC","model":"Vandura 3500","year":1993,"color":"Maroon","stolen":"Never"},
{"id":483,"make":"GMC","model":"Sierra","year":2010,"color":"Red","stolen":"Seldom"},
{"id":484,"make":"Dodge","model":"Stratus","year":1996,"color":"Puce","stolen":"Weekly"},
{"id":485,"make":"BMW","model":"3 Series","year":1997,"color":"Yellow","stolen":"Never"},
{"id":486,"make":"Mitsubishi","model":"3000GT","year":1993,"color":"Pink","stolen":"Yearly"},
{"id":487,"make":"Jeep","model":"Cherokee","year":1993,"color":"Fuscia","stolen":"Often"},
{"id":488,"make":"Ford","model":"Escape","year":2012,"color":"Pink","stolen":"Seldom"},
{"id":489,"make":"Mercury","model":"Grand Marquis","year":1995,"color":"Puce","stolen":"Daily"},
{"id":490,"make":"Ford","model":"E350","year":2012,"color":"Fuscia","stolen":"Monthly"},
{"id":491,"make":"Chevrolet","model":"Suburban 1500","year":2003,"color":"Teal","stolen":"Often"},
{"id":492,"make":"Buick","model":"Coachbuilder","year":1995,"color":"Goldenrod","stolen":"Weekly"},
{"id":493,"make":"Chevrolet","model":"Impala","year":1994,"color":"Purple","stolen":"Yearly"},
{"id":494,"make":"Dodge","model":"Spirit","year":1994,"color":"Green","stolen":"Weekly"},
{"id":495,"make":"Chevrolet","model":"Monte Carlo","year":2007,"color":"Indigo","stolen":"Once"},
{"id":496,"make":"Audi","model":"A8","year":2008,"color":"Pink","stolen":"Weekly"},
{"id":497,"make":"Lexus","model":"IS","year":2006,"color":"Goldenrod","stolen":"Weekly"},
{"id":498,"make":"Mitsubishi","model":"Galant","year":1985,"color":"Pink","stolen":"Seldom"},
{"id":499,"make":"Mitsubishi","model":"Mirage","year":1989,"color":"Orange","stolen":"Never"},
{"id":500,"make":"Ford","model":"Transit Connect","year":2011,"color":"Green","stolen":"Often"}];

const ui = document.getElementById("uiTable");

cars.forEach(car => {
    ui.innerHTML += `<tr><td>${car.make}</td><td>${car.model}</td><td>${car.year}</td><td>${car.color}</td><td>${car.stolen}</td></tr>`;
})

document.getElementById("send").addEventListener("click", () => {
    cars.forEach(car => {
        const newDoc = firestore.collection("cars").doc('' + car.id);
        const newData = {
            Make: car.make,
            Model: car.model,
            Year: car.year,
            Color: car.color,
            Stolen: car.stolen
        }
        newDoc.set(newData).then(() => console.log("success"));
    });
});
